In [1]:
import numpy as np

In [2]:
from sklearn.datasets import load_iris

In [3]:
iris = load_iris()

In [6]:
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [8]:
X = iris.data

In [9]:
y = iris.target

In [10]:
from sklearn.model_selection import train_test_split

In [12]:
from keras.utils import to_categorical

Using TensorFlow backend.
C:\Users\rithw\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\rithw\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\rithw\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\rithw\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py

In [13]:
y= to_categorical(y)

In [14]:
y

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [24]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [25]:
from sklearn.preprocessing import MinMaxScaler

In [26]:
scaler = MinMaxScaler()

In [27]:
scaler.fit(X_train)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [28]:
scaled_X_train = scaler.transform(X_train)

In [30]:
scaled_X_train

array([[0.55555556, 0.29166667, 0.67857143, 0.70833333],
       [0.25      , 0.58333333, 0.05357143, 0.04166667],
       [0.52777778, 0.375     , 0.57142857, 0.5       ],
       [0.94444444, 0.33333333, 1.        , 0.79166667],
       [0.02777778, 0.41666667, 0.03571429, 0.04166667],
       [0.19444444, 0.5       , 0.01785714, 0.04166667],
       [0.94444444, 0.41666667, 0.89285714, 0.91666667],
       [0.5       , 0.375     , 0.64285714, 0.54166667],
       [0.22222222, 0.625     , 0.05357143, 0.08333333],
       [0.36111111, 0.41666667, 0.60714286, 0.58333333],
       [0.16666667, 0.66666667, 0.05357143, 0.        ],
       [0.44444444, 0.5       , 0.66071429, 0.70833333],
       [0.22222222, 0.54166667, 0.10714286, 0.16666667],
       [0.75      , 0.5       , 0.64285714, 0.54166667],
       [0.80555556, 0.66666667, 0.89285714, 1.        ],
       [0.36111111, 0.29166667, 0.55357143, 0.5       ],
       [0.25      , 0.875     , 0.07142857, 0.        ],
       [0.55555556, 0.54166667,

In [32]:
from keras.models import Sequential
from keras.layers import Dense

In [46]:
model = Sequential()

In [47]:
model.add(Dense(8, input_dim = 4, activation="relu"))
model.add(Dense(16, activation="relu"))
model.add(Dense(3, activation="softmax"))
model.compile(loss="categorical_crossentropy", optimizer="adam", metrics=["accuracy"])

In [48]:
model.summary()

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_14 (Dense)             (None, 8)                 40        
_________________________________________________________________
dense_15 (Dense)             (None, 16)                144       
_________________________________________________________________
dense_16 (Dense)             (None, 3)                 51        
Total params: 235
Trainable params: 235
Non-trainable params: 0
_________________________________________________________________


In [50]:
model.fit(scaled_X_train, y_train, epochs=150, verbose=2)

Epoch 1/150
 - 0s - loss: 1.1633 - accuracy: 0.0179
Epoch 2/150
 - 0s - loss: 1.1526 - accuracy: 0.0000e+00
Epoch 3/150
 - 0s - loss: 1.1424 - accuracy: 0.0000e+00
Epoch 4/150
 - 0s - loss: 1.1321 - accuracy: 0.2411
Epoch 5/150
 - 0s - loss: 1.1225 - accuracy: 0.3214
Epoch 6/150
 - 0s - loss: 1.1128 - accuracy: 0.3214
Epoch 7/150
 - 0s - loss: 1.1038 - accuracy: 0.3214
Epoch 8/150
 - 0s - loss: 1.0949 - accuracy: 0.3304
Epoch 9/150
 - 0s - loss: 1.0857 - accuracy: 0.3393
Epoch 10/150
 - 0s - loss: 1.0764 - accuracy: 0.3661
Epoch 11/150
 - 0s - loss: 1.0667 - accuracy: 0.3750
Epoch 12/150
 - 0s - loss: 1.0564 - accuracy: 0.3839
Epoch 13/150
 - 0s - loss: 1.0463 - accuracy: 0.4107
Epoch 14/150
 - 0s - loss: 1.0358 - accuracy: 0.5089
Epoch 15/150
 - 0s - loss: 1.0251 - accuracy: 0.5536
Epoch 16/150
 - 0s - loss: 1.0140 - accuracy: 0.6429
Epoch 17/150
 - 0s - loss: 1.0028 - accuracy: 0.7054
Epoch 18/150
 - 0s - loss: 0.9908 - accuracy: 0.7411
Epoch 19/150
 - 0s - loss: 0.9784 - accuracy: 0

In [52]:
scaled_X_test = scaler.transform(X_test)

In [53]:
predictions = model.predict_classes(scaled_X_test)

In [56]:
predictions = to_categorical(predictions)

In [57]:
predictions

array([[1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.]], dtype=float32)

In [55]:
y_test

array([[1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]], dtype=float32)

In [58]:
from sklearn import metrics

In [60]:
print(metrics.classification_report(y_test, predictions))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        11
           1       0.89      0.62      0.73        13
           2       0.72      0.93      0.81        14

   micro avg       0.84      0.84      0.84        38
   macro avg       0.87      0.85      0.85        38
weighted avg       0.86      0.84      0.84        38
 samples avg       0.84      0.84      0.84        38



In [61]:
print(metrics.accuracy_score(y_test, predictions))

0.8421052631578947


In [62]:
predictions = predictions.argmax(axis=1)
y_test = y_test.argmax(axis=1)

In [63]:
print(metrics.confusion_matrix(y_test, predictions))

[[11  0  0]
 [ 0  8  5]
 [ 0  1 13]]


In [64]:
model.save("mymodel.h5")

In [66]:
from keras.models import load_model

In [67]:
mymodel = load_model("mymodel.h5")

In [69]:
mymodel.summary()

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_14 (Dense)             (None, 8)                 40        
_________________________________________________________________
dense_15 (Dense)             (None, 16)                144       
_________________________________________________________________
dense_16 (Dense)             (None, 3)                 51        
Total params: 235
Trainable params: 235
Non-trainable params: 0
_________________________________________________________________
